### ISSUE TITLE
Twilight Forest Crash with Firefly

### ISSUE THREAD

**Issue by ashly138** [iChun/Shatter#26]
https://gist.github.com/ashly138/0837e302c308cd1b9a4e7e29ac829b2e

**Comment by iChun** [comment]
Perfect, thanks.

**Comment by beesyndicate** [comment]
Me too.... 

https://pastebin.com/EufEXxXZ 

Also ...Sir.... your mods are amazing! keep up the good work.

**Comment by beesyndicate** [comment]
I have also been getting a stack overflow on the server that I have not been able to figure out what it is coming from It did start at the same time that i added shatter and ichun core along with other mods. the server ws stable all night until I just crashed my client killing the fire fly.  all I have is the server console output because the server just sort of stalls out but never actually crashes  I wonder if these things are related I think I will remove ichun core and mods that depend on it and see what happens. 

https://pastebin.com/tnG34qMq
